#!/bin/bash

#bs2     joseph@172.16.245.130:/home/joseph/.repo/ligand.git (fetch)
#bs2     joseph@172.16.245.130:/home/joseph/.repo/ligand.git (push)
#oalan   git@T1JNR3GLB01.wneweb.com.tw:jnr360/ligand.git (fetch)
#oalan   git@T1JNR3GLB01.wneweb.com.tw:jnr360/ligand.git (push)
#origin  https://gitlab.zoba.cc/junghaolin/ligand.git (fetch)
#origin  https://gitlab.zoba.cc/junghaolin/ligand.git (push)

if [ ! "$(basename $(pwd))" = "ligand" ]; then
  echo Not in a folder named ligand, exit.
  exit
fi
git push -u origin master
git push -u oalan 2wlag:main
git push -u bs2 master:main
git branch -f 2wlag $(git rev-list -n 1 --before="2 weeks ago" master)
git push oalan 2wlag:main
git push origin master:master
git push bs2 master:main
